<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\ChildEmbeddedForm' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/src/AppBundle/Form/ChildEmbeddedForm.php';

return $this->services['AppBundle\Form\ChildEmbeddedForm'] = new \AppBundle\Form\ChildEmbeddedForm();
