<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR05ixqi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR05ixqi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR05ixqi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR05ixqi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR05ixqi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'R05ixqi',
    'container.build_id' => '40fad8ba',
    'container.build_time' => 1550323521,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerR05ixqi');
